#!/bin/bash

function brief()
{
    echo "--aarch64-version=[8|8.2|9]"
}

function help()
{
    brief
    cat <<EOF
    This option is used to specify one of the following AArch64 version presets.
    Specifying one of these presets will cause preselected '-machine' and '-cpu'
    arguments to be used for the corresponding version.

    This option only has an effect for QEMU AArch64 VMs.

    Supported AArch64 version presets include the following:
        8:   ARMv8-A    (-machine virt-4.2 -cpu cortex-a57)
        8.2: ARMv8.2-A  (-machine virt-7.2 -cpu cortex-a76)
        9:   ARMv9.0-A  (-machine virt-8.2 -cpu cortex-a710)

    Note that the cortex-a76 and cortex-a710 CPUs may require you to update your
    QEMU version. We recommend upgrading to QEMU v9.2+.

    If unspecified, the default AArch64 version preset is '8'.
EOF
}

function validate()
{
    if [ "$OPT_AARCH64_VERSION" == "8" ] ||
       [ "$OPT_AARCH64_VERSION" == "8.2" ] ||
       [ "$OPT_AARCH64_VERSION" == "9" ]; then
        exit 0
    else
        echo "Invalid --aarch64-version value: $OPT_AARCH64_VERSION"
        brief
        exit 1
    fi
}

case "$1" in
    brief)
        brief;;
    help)
        help;;
    validate)
        validate;;
    default)
        echo 8;;
esac
