#!/bin/bash

function brief()
{
    echo "--arch=[x86_64|aarch64le]"
}

function help()
{
    brief
    cat <<EOF
    Architecture to build for.  For VMWare and VirtualBox, only x86_64 is supported.

    The default is x86_64.
EOF
}

function validate()
{
    rc=0
    if [ "$OPT_ARCH" != "x86_64" -a "$OPT_ARCH" != "aarch64le" ]; then
        echo "--arch not one of x86_64 or aarch64le"
        rc=1
    fi
    return $rc
}

case "$1" in
    brief)
        brief;;
    help)
        help;;
    validate)
        validate;;
    default)
        echo x86_64;;
esac
