#!/bin/bash

function brief()
{
    echo "--qtsafefs=[yes|no]"
}

function help()
{
    brief
    cat <<EOF
    If yes, the system partition is read-only and uses the QNX trusted
    filesystem for safety driver (qtsafefsd).

    The default is no.
EOF
}

function validate() {
    if [ "$OPT_QTSAFEFS" = yes -o "$OPT_QTSAFEFS" = no ]; then
        if [ "$OPT_QTSAFEFS" = yes -a "$OPT_QTD" = yes ]; then
            echo "--qtd and --qtsafefs are mutually exclusive"
            exit 1
        fi
        if [ "$OPT_QTSAFEFS" = yes ] && ! which openssl &> /dev/null; then
            echo "--qtsafefs requires the openssl command line tool"
            exit 1
        fi
        exit 0
    else
        echo "--qtsafefs must be set to 'yes' or 'no'"
        exit 1
    fi
}

function configure()
{
    rm -f output/option_files/*.OPT_QTSAFEFS
    if [ "$OPT_QTSAFEFS" = yes ]; then
        cat >output/option_files/ifs_files.OPT_QTSAFEFS <<EOF
#############################################
### qtsafefs
#############################################
qtsafefs_public_key.pem=local/misc_files/qtsafefs_public_key.pem
qtsafefsd=bin/qtsafefsd
EOF
        if [ ! -e local/misc_files/qtsafefs_public_key.pem -o ! -e local/misc_files/qtsafefs_private_key.pem ]; then
            echo Generating qtsafefs private/public key
            # Of course for a real system, you'd take care to keep your private key private
            openssl ecparam -name prime256v1 -param_enc explicit -no_seed -out ec_params.pem -outform PEM
            openssl genpkey -paramfile ec_params.pem -out local/misc_files/qtsafefs_private_key.pem
            rm ec_params.pem
            openssl pkey -in local/misc_files/qtsafefs_private_key.pem -pubout -out local/misc_files/qtsafefs_public_key.pem
        fi
    fi

    exit 0
}

case "$1" in
    brief)
        brief;;
    help)
        help;;
    validate)
        validate;;
    configure)
        configure;;
    default)
        echo no;;
esac
