#!/bin/sh
# Script that installs system and data file systems on boot.

echo ============================================================
echo Installing new file systems

# If we happen to have slm running, kill it off
slay -fs SIGKILL slm

ln -sPf /proc/boot/toybox /proc/boot/cp

cp /system/*.part /dev/shmem
cp /system/part.info /dev/shmem
cp /system/systemupdate.sh /dev/shmem
cp /system/updatefs.sh /dev/shmem
cd /dev/shmem

/bin/sh /dev/shmem/systemupdate.sh
