# features.properties
# contains externalized strings for feature.xml
# "%foo" in feature.xml corresponds to the key "foo" in this file
# java.io.Properties file (ISO 8859-1 with "" escapes)
# This file should be translated.

# "featureName" property - name of the feature
featureName=QNX Software Development Platform Documentation

# "providerName" property - name of the company that provides the feature
providerName=BlackBerry Limited

# "updateSiteName" property - label for the update site
updateSiteName=QNX update site

# "description" property - description of the feature
description=QNX Software Development Platform Documentation

# copyright
copyright=Copyright (c) 2002-2021 BlackBerry Limited

# "license" property - text of the "Feature Update License"
# should be plain text version of license agreement pointed to be "licenseURL"
# Elena recommended to comment out.
#license=
# "licenseURL" property - URL of the "Feature License"
# do not translate value - just change to point to a locale-specific HTML page
# Elena recommended to comment out.
#licenseURL=

