set(CMAKE_SYSTEM_NAME QNX)
set(CMAKE_SYSTEM_VERSION 8.0.0)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_C_COMPILER qcc)
set(CMAKE_C_FLAGS "-Vgcc_ntoaarch64le" CACHE STRING "")
set(CMAKE_CXX_COMPILER q++)
set(CMAKE_CXX_FLAGS "-Vgcc_ntoaarch64le" CACHE STRING "")

set(CMAKE_SYSROOT $ENV{QNX_TARGET})
set(CMAKE_FIND_ROOT_PATH $ENV{QNX_TARGET})
