new_local_repository(
    name = "dlt_daemon",
    path = "/home/prathik/dlt-daemon/build",
    build_file_content = """
cc_library(
    name = "dlt_includes",
    hdrs = glob(["include/**/*.h"]),
    includes = ["include"],
    visibility = ["//visibility:public"],
)
""",
)

new_local_repository(
    name = "qnx_sdk",
    path = "/home/prathik/qnx800/target/qnx",
    build_file_content = """
cc_library(
    name = "qnx_includes",
    hdrs = glob(["usr/include/**/*.h"]),
    includes = ["usr/include"],
    visibility = ["//visibility:public"],
)
""",
)