#!/bin/bash

. $TOOL_DIR/functions

export SCRIPT_DIR=`dirname $0 | sed -e 's!^\(.\):!/cygdrive/\1/!' -e 's!\\\\!/!g'`

function validate() {
	status=0
	if [ "$OPT_ARCH" != "x86_64" ]; then
		echo "Don't support $OPT_ARCH on VMWare.  Use '--arch=x86_64'"
		status=1
	fi
	if ! check_dependency lib/dll/pci/pci_hw-Intel_x86.so '--type=vmware requires the "Connectivity - PCI HW Module x86" package'; then
		status=1
	fi
	if [ "${OPT_GRAPHICS}" = yes ]; then
		if ! check_dependency usr/lib/graphics/vmwgfx-drm/gpu_drm-vmwgfx.so '--graphics=yes requires the "Screen Board Support VMware (vmwgfx)" package'; then
			status=1
		fi
	fi
	exit $status
}

function configure()
{
	rm -f output/option_files/options.opt_type_vmware

	echo BUILD_SCRIPT=`dirname $SCRIPT_DIR`/vmware_postbuild >>output/option_files/options.opt_type_vmware
}

case "$1" in
	validate)
		validate;;
	configure)
		configure;;
esac
