#!/bin/bash

function brief()
{
    echo "--xxx=[yes|no]"
}

function help()
{
    brief
    cat <<EOF
    This option does something or other
EOF
}

function validate() {
    if [ OK ]; then
        exit 0
    else
        echo "--xxx must be set to 'yes' or 'no'"
        exit 1
    fi
}

function configure()
{
    Create or remove files in output/option_files to have files added to ifs,
    system or data partitions or commands executed at startup.  The files must
    start with the following prefixes:

        definitions boot ifs_env ifs_start post_start profile ifs_files data_files
        system_files slm passwd_file shadow_file group_file uids options

    See README.customize for how files must be named. For option scripts, it is
    the convention that they use the name of the option as the suffix, for
    example:

        system_files.opt_sample

    Usually the configure command is executed only when options change or after
    a clean.  By changing the time on the file associated with the option, it
    can be executed each time.  For example:

    touch -t 200001010000 output/option_files/opt_sample

    if you do this, you should return 1 if the build files should be regenerated.

    exit 0
}

case "$1" in
	brief)
		brief;;
	help)
		help;;
	validate)
		validate;;
	configure)
		configure;;
	default)
		echo no;;
esac
