#!/bin/bash

export SCRIPT_DIR=`dirname $0 | sed -e 's!^\(.\):!/cygdrive/\1/!' -e 's!\\\\!/!g'`

if [ ! -e local/vmware_files ]; then
	mkdir local/vmware_files
fi
if [ ! -e local/vmware_files/vmware.vmx ]; then
	cp ${SCRIPT_DIR}/vmware.vmx local/vmware_files
	touch local/vmware_files/qnx.params
	CLEAN=1
fi
if [ ! -e local/misc_files/cleanup.vmware ]; then
	cp ${SCRIPT_DIR}/cleanup.vmware local/misc_files
fi

# Version used to detect when parameters might be out of sync with new versions of
# mkqnximage
CUR_VERSION=1

UPDATE_PARAMS=

unset BOOT_MODE
unset HOSTNAME
unset NUM_CPU
unset MACADDR
unset VERSION
if [ -z "${CLEAN}" ]; then
	. local/vmware_files/qnx.params
fi

sed_params=()

if [ "${IMAGE_TYPE}" != "${BOOT_MODE}" ]; then
	if [ "${IMAGE_TYPE}" = uefi ]; then
		if ! grep firmware local/vmware_files/vmware.vmx; then
			echo 'firmware = "efi"' >>local/vmware_files/vmware.vmx
			cat >>local/vmware_files/vmware.vmx <<EOF
serial0.fileType = "file"
serial0.fileName = "../../output/console.log"
serial0.present = "TRUE"
EOF
		fi
		UPDATE_PARAMS=1
	else
		sed_params=("${sed_params[@]}" -e '/firmware/d' -e '/serial0/d')
	fi
fi
if [ "${OPT_HOSTNAME}" != "${HOSTNAME}" ]; then
	sed_params=("${sed_params[@]}" -e "s/^displayName =.*/displayName = \"$OPT_HOSTNAME\"/")
fi
if [ "${OPT_CPU}" != "${NUM_CPU}" ]; then
	sed_params=("${sed_params[@]}" -e "s/^numvcpus =.*/numvcpus = \"$OPT_CPU\"/")
fi
if [ "${OPT_MACADDR}" != "${MACADDR}" ]; then
	sed_params=("${sed_params[@]}" -e "s/^ethernet0.address =.*/ethernet0.address = \"$OPT_MACADDR\"/")
fi
if [ "${VERSION}" != "$CUR_VERSION" ]; then
	sed_params=("${sed_params[@]}" -e "s/^ethernet0.virtualDev =.*/ethernet0.virtualDev = \"vmxnet3\"/")
fi

if [ ${#sed_params[@]} -gt 0 ]; then
	sed -Ei.bak "${sed_params[@]}" local/vmware_files/vmware.vmx
	# Get rid of the backup file created by sed.  While sed allows you to skip creation of the
	# backup file, it differs across OSes.
	rm -f local/vmware_files/vmware.vmx.bak
	UPDATE_PARAMS=1
fi

if [ -n "$UPDATE_PARAMS" ]; then
	rm local/vmware_files/qnx.params
	echo BOOT_MODE=$IMAGE_TYPE >>local/vmware_files/qnx.params
	echo HOSTNAME=$OPT_HOSTNAME >>local/vmware_files/qnx.params
	echo NUM_CPU=$OPT_CPU >>local/vmware_files/qnx.params
	echo MACADDR=$OPT_MACADDR >>local/vmware_files/qnx.params
	echo VERSION=$CUR_VERSION >>local/vmware_files/qnx.params
fi
