#!/bin/bash

CLEANED_ARGS=()
DEP_FILE=""

# 1. Unpack `@param` files generated by Bazel
RAW_ARGS=()
for arg in "$@"; do
    if [[ "$arg" == @* ]]; then
        PARAM_FILE="${arg#@}"
        if [[ -f "$PARAM_FILE" ]]; then
            while IFS= read -r line || [[ -n "$line" ]]; do
                RAW_ARGS+=("$line")
            done < "$PARAM_FILE"
        else
            RAW_ARGS+=("$arg")
        fi
    else
        RAW_ARGS+=("$arg")
    fi
done

# 2. Inject QNX system defaults and local library paths
# Driver flag
# Driver flag
CLEANED_ARGS+=("-Y_gpp")

# Include paths
CLEANED_ARGS+=("-I/home/prathik/qnx800/target/qnx/usr/include")
CLEANED_ARGS+=("-I/home/prathik/qnx800/QNX8_App/someip_app/lib/vsomeip/interface")

# Library search paths (-L)
CLEANED_ARGS+=("-L/home/prathik/qnx800/target/qnx/usr/lib")
CLEANED_ARGS+=("-L/home/prathik/qnx800/QNX8_App/someip_app/lib")
CLEANED_ARGS+=("-L/home/prathik/qnx800/QNX8_App/someip_app/lib/vsomeip/build_qnx_aarch64")
CLEANED_ARGS+=("-L/home/prathik/qnx800/QNX8_App/dlt-daemon/build/src/lib")
CLEANED_ARGS+=("-L/home/prathik/qnx800/boost_qnx_aarch64/lib")  # <--- ADDED BOOST PATH

# Linker rpath-link paths (resolves secondary dynamic dependencies during link time)
CLEANED_ARGS+=("-Wl,-rpath-link,/home/prathik/qnx800/target/qnx/usr/lib")
CLEANED_ARGS+=("-Wl,-rpath-link,/home/prathik/qnx800/QNX8_App/someip_app/lib/vsomeip/build_qnx_aarch64")
CLEANED_ARGS+=("-Wl,-rpath-link,/home/prathik/qnx800/boost_qnx_aarch64/lib")  # <--- ADDED BOOST RPATH-LINK

# 3. Filter arguments
i=0
while [[ $i -lt ${#RAW_ARGS[@]} ]]; do
    curr="${RAW_ARGS[$i]}"
    
    case "$curr" in
        # Drop raw -rpath and its argument
        -rpath)
            ((i+=2))
            continue
            ;;
        -rpath,*|-Wl,-rpath,*)
            ((i++))
            continue
            ;;
        -Wl,-rpath)
            ((i+=2))
            continue
            ;;
        # Drop Bazel's dynamic $ORIGIN runfile paths
        \$ORIGIN*|*\$ORIGIN*)
            ((i++))
            continue
            ;;
        -MF)
            DEP_FILE="${RAW_ARGS[$((i+1))]}"
            ((i+=2))
            continue
            ;;
        -MD|-MMD|-MP)
            ((i++))
            continue
            ;;
        -Wthread-safety|-Wself-assign|-fcolor-diagnostics|-Wno-free-nonheap-object)
            ((i++))
            continue
            ;;
        *)
            CLEANED_ARGS+=("$curr")
            ((i++))
            ;;
    esac
done

if [ -n "$DEP_FILE" ]; then
    CLEANED_ARGS+=("-Wp,-MD,${DEP_FILE}")
fi

# 4. Execute qcc with retry mechanism
MAX_RETRIES=3
RETRY_COUNT=0
RC=1

while [ $RETRY_COUNT -lt $MAX_RETRIES ] && [ $RC -ne 0 ]; do
    /home/prathik/qnx800/host/linux/x86_64/usr/bin/qcc "${CLEANED_ARGS[@]}"
    RC=$?
    
    if [ $RC -ne 0 ]; then
        rm -f /home/prathik/.qnx/license/licenses.lck 2>/dev/null
        sleep 1
        ((RETRY_COUNT++))
    fi
done

# Filter dependency outputs for Bazel sandbox compatibility
if [ $RC -eq 0 ] && [ -n "$DEP_FILE" ] && [ -f "$DEP_FILE" ]; then
    sed -i 's| /home/prathik/[^ ]*||g' "$DEP_FILE"
    sed -i 's|^/home/prathik/[^ ]*||g' "$DEP_FILE"
    sed -i '/^[[:space:]]*\\*$/d' "$DEP_FILE"
fi

exit $RC