#!/bin/bash

. $TOOL_DIR/functions

firmware_files=(
	bcm2711-rpi-4-b.dtb
	brcmfmac43455-sdio.raspberrypi,4-model-b.txt
	cyfmac43455-sdio.bin
	cyfmac43455-sdio.clm_blob
	fixup4.dat
	start4.elf
)

function validate()
{
	status=0
	missing=()
	for f in ${firmware_files[@]}; do
		if ! check_dependency $f; then
			missing+=($f)
		fi
	done
	if [ "${#missing[@]}" -gt 0 ]; then
		sep=
		echo -n "Missing Raspberry Pi firmware files: "
		for f in ${missing[@]}; do
			echo -n $sep $f
			sep=", "
		done
		echo
		echo Perhaps add the directory containing the firmware to the list of directories
		echo for the --repos option.
		status=1
	fi

	exit $status
}

case "$1" in
	validate)
		validate;;
esac
