begin winmgr
  begin globals
    alloc-config = stdbuf
    blit-config = sw
  end globals

  begin virtual display
    id_string = virtual-1
    video-mode = 1280 x 768 @ 60
    format = rgba8888
    usage =  sw
  end virtual display
end winmgr
