load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

# Local header-only library for nlohmann json
cc_library(
    name = "nlohmann_json",
    hdrs = ["include/nlohmann/json.hpp"],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "execution_manager",
    srcs = [
        "em_main.cpp",
    ],
    copts = [
        "-std=c++17",
        "-lang-c++",
    ],
    linkopts = [
        "-lsocket",
        "-ldlt",
        "-L/home/prathik/qnx800/QNX8_App/dlt-daemon/build/src/lib",
        "-lc++",
        "-lm",
    ],
    deps = [
        ":nlohmann_json",
    ],
)