load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

# 1. Local header-only library for nlohmann json
cc_library(
    name = "nlohmann_json",
    hdrs = ["include/nlohmann/json.hpp"],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
)

# 2. Local library exposing DLT headers into the Bazel Sandbox
cc_library(
    name = "dlt_lib",
    hdrs = glob([
        "dlt-daemon/include/**/*.h",
        "dlt-daemon/build/include/**/*.h",
    ]),
    includes = [
        "dlt-daemon/include",
        "dlt-daemon/include/dlt",
        "dlt-daemon/build/include",
        "dlt-daemon/build/include/dlt",
    ],
    visibility = ["//visibility:public"],
)

# 3. Target Binary
cc_binary(
    name = "execution_manager",
    srcs = [
        "em_main.cpp",
    ],
    copts = [
        "-std=c++17",
    ],
    linkopts = [
        "-lsocket",
        "-ldlt",
        "-L/home/prathik/qnx800/QNX8_App/dlt-daemon/build/src/lib",
        "-lc++",
        "-lm",
    ],
    deps = [
        ":nlohmann_json",
        ":dlt_lib",
    ],
)