# WORKSPACE

new_local_repository(
    name = "dlt_external",
    path = "/home/prathik/qnx800/QNX8_App/dlt-daemon",
    build_file_content = """
load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "dlt_headers",
    hdrs = glob([
        "include/**/*.h",
        "build/include/**/*.h",
    ]),
    includes = [
        "include",
        "include/dlt",
        "build/include",
        "build/include/dlt",
    ],
)
""",
)

new_local_repository(
    name = "em_external",
    path = "/home/prathik/qnx800/QNX8_App/em",
    build_file_content = """
load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "json_headers",
    hdrs = glob(["include/**/*.hpp", "include/**/*.h"]),
    includes = ["include"],
)
""",
)
